cloudflare/research.cloudflare.com

people/kris-kwiatkowski.md
Small update to make it clear I'm not anymore part of Cloudflare (although had a great time there).
=> Add Kris's current role.

people/ian-mcquoid.md
Updated bio to reflect current role instead of role while at cloudflare.
=> Update to Ian's bio

outreach/events/2022-02-21-post-quantum-blog-series.md, projects/post-quantum-cryptography.md
=> More post-quantum

outreach/academic-programs/interns/tim-alberdingkthijm.md
Add a brief biography for Tim. Edit at your leisure. 🙂
=> Add a bio for Tim

outreach/academic-programs/interns/petros-gigis.md
Add Gigis Petros profile to the interns.
=> add Gigis Petros profile

package.json
Removing npm as a dependency and all dependencies moved to devDependencies
=> moving to devDependencies

_data/interests.js
=> Add application interest area

people/suleman-ahmad.md, projects/application-privacy/safer-passwords.md, projects/network-privacy/ech.md, projects/network-privacy/tls.md
Additionally adds Automatic Origin Security setting blog related to SSL/TLS Recommender to TLS project file.
=> Update Suleman Ahmad's profile and add new blog post to TLS project

publications/Eaton2023.md, publications/Hesse2023.md, publications/Ladd2023.md, publications/Policharla2023.md
Ladd2023.md
Eaton2023.md
Policharla2023.md
Hesse2023.md
=> Adding new publications

publications/Wood2023.md
=> Add IEEE column

publications/Faz-Hernandez2023.md
New RFC published
I couldn't update the other PR
=> Add RFC-9380.

_data/blogposts.js
=> use base_url variable

_includes/person_header.njk
=> Fixes X image logo

about/people/index.njk, projects/application-privacy/privacy-pass.md, projects/application-privacy/safer-passwords.md, projects/applied-cryptography/circl.md, publications/Celi2024.md, publications/Davidson2024.md, publications/Pauly2024.md
=> adding Privacy Pass RFCs

projects/future-networks/geokmv2.md
Adds info about Portunus system.
=> project: Add info about portunus system.

_data/interests.js, publications/Khor2024.md
Additionally adds new interest field for "Machine Learning".
=> Add PACMI'24 workshop paper publication

about/people/james-larisch.md
My blog post wasn't being picked up
=> Rename James' blog_author to james-larisch

outreach/academic-programs/interns/isaac-khor.md, publications/Khor2024.md
=> Add Isaac K to list of interns

outreach/academic-programs/interns/joao-leite.md
Adding my profile to the intern outreach page. Let me know if anything else is needed.
=> Add jleite intern profile

publications/Heimberger2024.md
Chris P.'s name was misspelled.
=> Fix author reference for Heimberger2024
